default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fiscal_flow_development
  username: xpto
  password: xpto

test:
  <<: *default
  database: fiscal_flow_test
  username: xpto
  password: xpto

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>