default: &default
  adapter: postgresql
  encoding: unicode
  username: xpto
  password: xpto

development:
  <<: *default
  database: fiscal_flow_development
  pool: 5

test:
  <<: *default
  database: fiscal_flow_test

production:
  <<: *default
  database: railway
  host: postgres.railway.internal
  port: 5432
  username: postgres
  password: sMApOUkcZkNLNsFXbEdCBSDZWiBkawox
