default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fiscal_flow_development
  username: xpto
  password: xpto

test:
  <<: *default
  database: fiscal_flow_test
  username: xpto
  password: xpto

production:
  url: postgresql://postgres.snmxbmbrpjiepecmadlh:MbugDaJkYWqdLqAeFPxMxQdWNxRTPwPP@aws-0-us-west-1.pooler.supabase.com:6543/postgres